### ISSUE TITLE
General TODO LIST

### ISSUE THREAD

**Issue by davidRFB** [dejimenezc/Peptide-MHCII#4]
- [x] Improve Pep_Strucutures.py @davidRFB 
- [ ] List of software to use.  @dejimenezc 
- [x] Check tleap execution @davidRFB 
- [ ] Define complete workflow (Image better :D )

**Comment by dejimenezc** [comment]
@davidRFB  Hey, Workflow is done. What you think about it? is something missing or is there something to pull off?

**Comment by davidRFB** [comment]
Cool :+1:  Any update in the execution of ADCP ? Did u already executed it locally ?
